name: CI/CD Pipeline

on:
  [push, pull_request] 

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1

      - name: Install dependencies
      run: sudo apt-get install -y build-essential

      - name: Install MPI
        run: sudo apt-get install -y mpich

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build

      - name: Run tests
        run: ctest --test-dir build

