name: CI/CD Pipeline

on:
  [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies for Singularity
        if: steps.cache-singularity.outputs.cache-hit != 'true'
        
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            uuid-dev \
            libgpgme11-dev \
            squashfs-tools \
            libseccomp-dev \
            wget \
            pkg-config \
            git \
            cryptsetup-bin \
            libfuse-dev \
            libfuse3-dev \
            sshpass
            
      - name: Install Go
        if: steps.cache-singularity.outputs.cache-hit != 'true'
        run: |
          export VERSION=1.21.0 OS=linux ARCH=amd64 && \
          wget https://dl.google.com/go/go$VERSION.$OS-$ARCH.tar.gz && \
          sudo tar -C /usr/local -xzvf go$VERSION.$OS-$ARCH.tar.gz && \
          echo 'export PATH=/usr/local/go/bin:$PATH' >> $GITHUB_ENV
          
      - name: Install Singularity
        if: steps.cache-singularity.outputs.cache-hit != 'true'
        run: |
          export VERSION=4.1.3 && \
          wget https://github.com/sylabs/singularity/releases/download/v${VERSION}/singularity-ce-${VERSION}.tar.gz && \
          tar -xzf singularity-ce-${VERSION}.tar.gz && \
          cd singularity-ce-${VERSION} && \
          ./mconfig && \
          make -C builddir && \
          sudo make -C builddir install 
          
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential sshpass

      - name: Build Singularity container
        run: |
          sudo singularity build my_container.sif singularity.def

      #- name: Transfer files to Galileo100
      #  env:
      #    SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      #  run: |
      #    sshpass -p "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no my_container.sif a08trb63@login.g100.cineca.it
          
      - name: Transfer files to Galileo100
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no a08trb63@login.g100.cineca.it 'cd /g100/home/usertrain/a08trb63/project && touch ciao.txt'


      #- name: Submit job to SLURM
       # env:
       #   SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
       # run: |
       #   sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no a08trb63@login.g100.cineca.it "sbatch job.sh"

     
