name: CI/CD Pipeline

on:
  [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1

      - name: Install dependencies
        run: sudo apt-get install -y build-essential

      - name: Install MPI
        run: sudo apt-get install -y mpich

      - name: Submodules init
        run: git submodule init

      - name: Submodules update
        run: git submodule update

      - name: Build
        run: ./build.sh

      - name: Run tests
        run: ctest --test-dir build

      - name: Install Singularity
        run: |
          sudo apt-get update
          sudo apt-get install -y singularity-container

      - name: Create Singularity definition file
        run: |
          echo "Bootstrap: library
          From: Ubuntu:18.04
          Stage: build

          %setup
              touch /file1
              touch \${SINGULARITY_ROOTFS}/file2

          %post
              git clone --recurse-submodules https://github.com/BiceMar/sweng_project_part_2.git
              sudo apt-get update && apt-get install -y mpich

          %runscripts
              echo \"Test run scripts\"

          %test
              echo \"looking for MPI...\"
              mpich
              grep -q NAME=\"Ubuntu\" /etc/os-release
              if [ \$? -eq 0 ]; then
                  echo \"Container base is Ubuntu as expected.\"
              else
                  echo \"Container base is not Ubuntu.\"
              fi

          %labels
              SWENG4HPC project v.1.0" > singularity.def

      - name: Build Singularity container
        run: |
          singularity build container.sif singularity.def

      - name: Test Singularity container
        run: |
          singularity test container.sif
