name: CI/CD Pipeline

on:
  [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Singularity
        uses: eWaterCycle/setup-singularity@v7

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential sshpass

      - name: Build Singularity container
        run: |
          sudo singularity build my_container.sif singularity.def

      #- name: Transfer files to Galileo100
      #  env:
      #    SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      #  run: |
      #    sshpass -p "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no my_container.sif a08trb63@login.g100.cineca.it
          
      - name: Transfer files to Galileo100
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no a08trb63@login.g100.cineca.it 'cd /g100/home/usertrain/a08trb63/project && touch ciao.txt'


      #- name: Submit job to SLURM
       # env:
       #   SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
       # run: |
       #   sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no a08trb63@login.g100.cineca.it "sbatch job.sh"

     
